package com.example.musicwebdav.infrastructure.persistence.mapper;

import com.example.musicwebdav.infrastructure.persistence.entity.TrackEntity;
import com.example.musicwebdav.infrastructure.persistence.model.SearchAlbumRow;
import com.example.musicwebdav.infrastructure.persistence.model.SearchArtistRow;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface SearchMapper {

    @Select({"<script>",
            "SELECT t.id, t.title, t.artist, t.album, t.source_path, t.duration_sec, t.has_lyric ",
            "FROM track t ",
            "WHERE t.is_deleted = 0 ",
            "<if test='keyword != null and keyword != \"\"'>",
            " AND (t.title LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.artist LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.album LIKE CONCAT('%', #{keyword}, '%')) ",
            "</if>",
            "ORDER BY ",
            "<if test='keyword != null and keyword != \"\"'>",
            " CASE ",
            "   WHEN LOWER(t.title) = LOWER(#{keyword}) THEN 0 ",
            "   WHEN LOWER(t.title) LIKE CONCAT(LOWER(#{keyword}), '%') THEN 1 ",
            "   WHEN LOWER(t.artist) = LOWER(#{keyword}) THEN 2 ",
            "   WHEN LOWER(t.album) = LOWER(#{keyword}) THEN 3 ",
            "   ELSE 9 ",
            " END, ",
            "</if>",
            " t.updated_at DESC, t.id DESC ",
            "LIMIT #{offset}, #{pageSize}",
            "</script>"})
    List<TrackEntity> selectSongPageAll(@Param("offset") int offset,
                                        @Param("pageSize") int pageSize,
                                        @Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT COUNT(1) ",
            "FROM track t ",
            "WHERE t.is_deleted = 0 ",
            "<if test='keyword != null and keyword != \"\"'>",
            " AND (t.title LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.artist LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.album LIKE CONCAT('%', #{keyword}, '%')) ",
            "</if>",
            "</script>"})
    long countSongAll(@Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT t.id, t.title, t.artist, t.album, t.source_path, t.duration_sec, t.has_lyric ",
            "FROM (",
            "  SELECT DISTINCT pt.track_id ",
            "  FROM playlist_track pt ",
            "  INNER JOIN playlist p ON p.id = pt.playlist_id ",
            "  WHERE p.is_deleted = 0",
            ") mine ",
            "INNER JOIN track t ON t.id = mine.track_id ",
            "WHERE t.is_deleted = 0 ",
            "<if test='keyword != null and keyword != \"\"'>",
            " AND (t.title LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.artist LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.album LIKE CONCAT('%', #{keyword}, '%')) ",
            "</if>",
            "ORDER BY ",
            "<if test='keyword != null and keyword != \"\"'>",
            " CASE ",
            "   WHEN LOWER(t.title) = LOWER(#{keyword}) THEN 0 ",
            "   WHEN LOWER(t.title) LIKE CONCAT(LOWER(#{keyword}), '%') THEN 1 ",
            "   WHEN LOWER(t.artist) = LOWER(#{keyword}) THEN 2 ",
            "   WHEN LOWER(t.album) = LOWER(#{keyword}) THEN 3 ",
            "   ELSE 9 ",
            " END, ",
            "</if>",
            " t.updated_at DESC, t.id DESC ",
            "LIMIT #{offset}, #{pageSize}",
            "</script>"})
    List<TrackEntity> selectSongPageMine(@Param("offset") int offset,
                                         @Param("pageSize") int pageSize,
                                         @Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT COUNT(1) ",
            "FROM (",
            "  SELECT DISTINCT pt.track_id ",
            "  FROM playlist_track pt ",
            "  INNER JOIN playlist p ON p.id = pt.playlist_id ",
            "  WHERE p.is_deleted = 0",
            ") mine ",
            "INNER JOIN track t ON t.id = mine.track_id ",
            "WHERE t.is_deleted = 0 ",
            "<if test='keyword != null and keyword != \"\"'>",
            " AND (t.title LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.artist LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.album LIKE CONCAT('%', #{keyword}, '%')) ",
            "</if>",
            "</script>"})
    long countSongMine(@Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT t.artist AS artist, ",
            "       COUNT(1) AS trackCount, ",
            "       COALESCE(MAX(CASE WHEN t.has_cover = 1 THEN t.id ELSE NULL END), MAX(t.id)) AS coverTrackId ",
            "FROM track t ",
            "WHERE t.is_deleted = 0 ",
            "  AND t.artist IS NOT NULL ",
            "  AND t.artist != '' ",
            "<if test='keyword != null and keyword != \"\"'>",
            " AND t.artist LIKE CONCAT('%', #{keyword}, '%') ",
            "</if>",
            "GROUP BY t.artist ",
            "ORDER BY ",
            "<if test='keyword != null and keyword != \"\"'>",
            " CASE ",
            "   WHEN LOWER(t.artist) = LOWER(#{keyword}) THEN 0 ",
            "   WHEN LOWER(t.artist) LIKE CONCAT(LOWER(#{keyword}), '%') THEN 1 ",
            "   ELSE 9 ",
            " END, ",
            "</if>",
            " MAX(t.updated_at) DESC, COUNT(1) DESC, t.artist ASC ",
            "LIMIT #{offset}, #{pageSize}",
            "</script>"})
    List<SearchArtistRow> selectArtistPage(@Param("offset") int offset,
                                           @Param("pageSize") int pageSize,
                                           @Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT COUNT(1) FROM (",
            "  SELECT t.artist ",
            "  FROM track t ",
            "  WHERE t.is_deleted = 0 ",
            "    AND t.artist IS NOT NULL ",
            "    AND t.artist != '' ",
            "  <if test='keyword != null and keyword != \"\"'>",
            "   AND t.artist LIKE CONCAT('%', #{keyword}, '%') ",
            "  </if>",
            "  GROUP BY t.artist",
            ") c",
            "</script>"})
    long countArtists(@Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT t.album AS album, t.artist AS artist, ",
            "       COUNT(1) AS trackCount, ",
            "       COALESCE(MAX(CASE WHEN t.has_cover = 1 THEN t.id ELSE NULL END), MAX(t.id)) AS coverTrackId ",
            "FROM track t ",
            "WHERE t.is_deleted = 0 ",
            "  AND t.album IS NOT NULL ",
            "  AND t.album != '' ",
            "<if test='artist != null and artist != \"\"'>",
            " AND t.artist = #{artist} ",
            "</if>",
            "<if test='keyword != null and keyword != \"\"'>",
            " AND (t.album LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.title LIKE CONCAT('%', #{keyword}, '%')) ",
            "</if>",
            "GROUP BY t.album, t.artist ",
            "ORDER BY ",
            "<if test='keyword != null and keyword != \"\"'>",
            " CASE ",
            "   WHEN LOWER(t.album) = LOWER(#{keyword}) THEN 0 ",
            "   WHEN LOWER(t.album) LIKE CONCAT(LOWER(#{keyword}), '%') THEN 1 ",
            "   ELSE 9 ",
            " END, ",
            "</if>",
            " MAX(t.updated_at) DESC, COUNT(1) DESC, t.album ASC ",
            "LIMIT #{offset}, #{pageSize}",
            "</script>"})
    List<SearchAlbumRow> selectAlbumPage(@Param("artist") String artist,
                                         @Param("offset") int offset,
                                         @Param("pageSize") int pageSize,
                                         @Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT COUNT(1) FROM (",
            "  SELECT t.album, t.artist ",
            "  FROM track t ",
            "  WHERE t.is_deleted = 0 ",
            "    AND t.album IS NOT NULL ",
            "    AND t.album != '' ",
            "  <if test='artist != null and artist != \"\"'>",
            "   AND t.artist = #{artist} ",
            "  </if>",
            "  <if test='keyword != null and keyword != \"\"'>",
            "   AND (t.album LIKE CONCAT('%', #{keyword}, '%') ",
            "     OR t.title LIKE CONCAT('%', #{keyword}, '%')) ",
            "  </if>",
            "  GROUP BY t.album, t.artist",
            ") c",
            "</script>"})
    long countAlbums(@Param("artist") String artist,
                     @Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT t.id, t.title, t.artist, t.album, t.source_path, t.duration_sec, t.has_lyric ",
            "FROM track t ",
            "WHERE t.is_deleted = 0 ",
            "  AND t.artist = #{artist} ",
            "<if test='keyword != null and keyword != \"\"'>",
            " AND (t.title LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.album LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.artist LIKE CONCAT('%', #{keyword}, '%')) ",
            "</if>",
            "ORDER BY ",
            "<if test='keyword != null and keyword != \"\"'>",
            " CASE ",
            "   WHEN LOWER(t.title) = LOWER(#{keyword}) THEN 0 ",
            "   WHEN LOWER(t.title) LIKE CONCAT(LOWER(#{keyword}), '%') THEN 1 ",
            "   ELSE 9 ",
            " END, ",
            "</if>",
            " t.updated_at DESC, t.id DESC ",
            "LIMIT #{offset}, #{pageSize}",
            "</script>"})
    List<TrackEntity> selectArtistTrackPage(@Param("artist") String artist,
                                            @Param("offset") int offset,
                                            @Param("pageSize") int pageSize,
                                            @Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT COUNT(1) ",
            "FROM track t ",
            "WHERE t.is_deleted = 0 ",
            "  AND t.artist = #{artist} ",
            "<if test='keyword != null and keyword != \"\"'>",
            " AND (t.title LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.album LIKE CONCAT('%', #{keyword}, '%') ",
            "   OR t.artist LIKE CONCAT('%', #{keyword}, '%')) ",
            "</if>",
            "</script>"})
    long countArtistTracks(@Param("artist") String artist,
                           @Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT t.artist ",
            "FROM track t ",
            "WHERE t.is_deleted = 0 ",
            "  AND t.artist IS NOT NULL ",
            "  AND t.artist != '' ",
            "  AND LOWER(t.artist) = LOWER(#{keyword}) ",
            "GROUP BY t.artist ",
            "ORDER BY COUNT(1) DESC ",
            "LIMIT 1",
            "</script>"})
    String selectExactArtist(@Param("keyword") String keyword);

    @Select({"<script>",
            "SELECT t.artist ",
            "FROM track t ",
            "WHERE t.is_deleted = 0 ",
            "  AND t.artist IS NOT NULL ",
            "  AND t.artist != '' ",
            "  AND t.artist LIKE CONCAT('%', #{keyword}, '%') ",
            "GROUP BY t.artist ",
            "ORDER BY ",
            " CASE WHEN LOWER(t.artist) LIKE CONCAT(LOWER(#{keyword}), '%') THEN 0 ELSE 1 END, ",
            " COUNT(1) DESC, t.artist ASC ",
            "LIMIT 1",
            "</script>"})
    String selectFuzzyArtist(@Param("keyword") String keyword);

    @Select("SELECT COUNT(1) FROM track t WHERE t.is_deleted = 0 AND t.artist = #{artist}")
    long countArtistTracksByName(@Param("artist") String artist);
}
